/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlttnn.view;

import qlttnn.dao.BillDAO;
import qlttnn.dao.UserDAO;
import qlttnn.model.*;

import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author ASUS
 */
public class BillFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillFrm.class.getName());
    private Registering registering;
    private Bill bill;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");  // THÊM
    private Map<Integer, User> teacherMap;
    private RegisterCourseFrm registerCourseFrm;
    /**
     * Creates new form BillFrm
     */
    public BillFrm(Registering registering, RegisterCourseFrm registerCourseFrm) {
        initComponents();
        this.registering = registering;
        this.registerCourseFrm = registerCourseFrm;
        Student student = registering.getStudent();
        UserDAO userDAO = new UserDAO();
        teacherMap = new HashMap<>();
        lblEnrollmentStaff.setText(registering.getUser().getFullName());
        lblBillingDate.setText(LocalDateTime.now().format(formatter));
        lblFullName.setText(student.getFullName());
        lblDateOfBirth.setText(student.getDateOfBirth().format(dateFormatter));
        lblIDCard.setText(student.getIdCard());
        lblEmail.setText(student.getEmail());
        lblAddress.setText(student.getAddress());
        lblToltalTuition.setText(String.valueOf(registering.getTotalTuition()));
        lblSaleOff.setText(String.valueOf(registering.getSaleOff()));



        DefaultTableModel defaultTableModel = (DefaultTableModel) tblRegisteredClass.getModel();
        defaultTableModel.setRowCount(0);
        int stt = 0;
        ArrayList<RegisteredClass> registeredClasses = this.registering.getRegisteredClasses();
        // Load teacher cho TẤT CẢ sessions của tất cả các registeredClass
        for (RegisteredClass rc : registeredClasses) {
            CourseClass cc = rc.getCourseClass();
            Map<Integer, User> classTeachers = userDAO.getTeacherForSessions(cc);
            teacherMap.putAll(classTeachers);
        }
        for (RegisteredClass rc: registeredClasses){
            CourseClass cc = rc.getCourseClass();
            Level level = cc.getLevel();
            Program program = level.getProgram();
            defaultTableModel.addRow(new Object[]{
                    ++stt,
                    cc.getClassName(),
                    program.getProgramName(),
                    level.getLevelName(),
                    cc.getBranch().getBranchName(),
                    cc.getStartDate(),
                    cc.getLevel().getTuition()
            });
        }
        DefaultTableModel defaultTableModelSession = (DefaultTableModel) tblSessionList.getModel();
        defaultTableModelSession.setRowCount(0);
        int st = 0;
        for (RegisteredClass rc: registeredClasses){
            CourseClass cc = rc.getCourseClass();
            ArrayList<Session> sessions = cc.getSessions();
            for(Session session: sessions) {
                Shift shift = session.getShift();
                defaultTableModelSession.addRow(new Object[]{
                        ++st,
                        cc.getClassName(),
                        session.getDate(),
                        shift.getShiftName(),
                        teacherMap.get(session.getId()).getFullName(),
                        session.getSkill(),
                        session.getClassRoom().getRoomName()
                });
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEnrollmentStaff = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBillingDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIDCard = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegisteredClass = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSessionList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jlabel10 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        lblPaymentAmount = new javax.swing.JLabel();
        cbxPaymentType = new javax.swing.JComboBox<>();
        txtPaymentAmount = new javax.swing.JTextField();
        lblPaymentType = new javax.swing.JLabel();
        lblToltalTuition = new javax.swing.JLabel();
        lblSaleOff = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hoá đơn");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Người tạo phiếu:  ");
        jPanel1.add(jLabel1);

        lblEnrollmentStaff.setBackground(new java.awt.Color(255, 255, 255));
        lblEnrollmentStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEnrollmentStaff.setText("Văn Thị Mai Linh");
        jPanel1.add(lblEnrollmentStaff);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ngày tạo phiếu:  ");
        jPanel1.add(jLabel2);

        lblBillingDate.setBackground(new java.awt.Color(255, 255, 255));
        lblBillingDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBillingDate.setText("07/05/2026");
        jPanel1.add(lblBillingDate);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin học viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        java.awt.GridBagLayout pnlStudentInfoLayout = new java.awt.GridBagLayout();
        pnlStudentInfoLayout.columnWidths = new int[] {0, 20, 0};
        pnlStudentInfoLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2.setLayout(pnlStudentInfoLayout);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel3, gridBagConstraints);

        lblFullName.setBackground(new java.awt.Color(255, 255, 255));
        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFullName.setText("Nguyễn Văn Bình");
        lblFullName.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblFullName, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày sinh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel4, gridBagConstraints);

        lblDateOfBirth.setBackground(new java.awt.Color(255, 255, 255));
        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDateOfBirth.setText("19/02/2005");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblDateOfBirth, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("CCCD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel5, gridBagConstraints);

        lblIDCard.setBackground(new java.awt.Color(255, 255, 255));
        lblIDCard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIDCard.setText("000123456789");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblIDCard, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("SĐT:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel6, gridBagConstraints);

        lblPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhone.setText("0123456789");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblPhone, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel7, gridBagConstraints);

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("hhtuann@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblEmail, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel8, gridBagConstraints);

        lblAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddress.setText("Hoằng Hoá - Thanh Hoá");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(lblAddress, gridBagConstraints);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách lớp học đăng ký", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblRegisteredClass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblRegisteredClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Tên lớp", "Chương trình", "Mức độ", "Cơ sở", "Ngày khai giảng", "Học phí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRegisteredClass);
        if (tblRegisteredClass.getColumnModel().getColumnCount() > 0) {
            tblRegisteredClass.getColumnModel().getColumn(0).setMaxWidth(30);
            tblRegisteredClass.getColumnModel().getColumn(2).setMinWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(2).setMaxWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(4).setMaxWidth(300);
            tblRegisteredClass.getColumnModel().getColumn(5).setMinWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách các buổi học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblSessionList.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblSessionList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Lớp học", "Ngày học", "Ca học", "Giáo viên", "Kĩ năng", "Phòng học"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSessionList);
        if (tblSessionList.getColumnModel().getColumnCount() > 0) {
            tblSessionList.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 20, 0};
        jPanel3Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel3.setLayout(jPanel3Layout);

        jlabel10.setBackground(new java.awt.Color(255, 255, 255));
        jlabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlabel10.setText("Khuyến mãi: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jlabel10, gridBagConstraints);

        jlabel9.setBackground(new java.awt.Color(255, 255, 255));
        jlabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlabel9.setText("Tổng tiền học phí:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jlabel9, gridBagConstraints);

        lblPaymentAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPaymentAmount.setText("Số tiền thanh toán lần này:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(lblPaymentAmount, gridBagConstraints);

        cbxPaymentType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyển khoản", "Tiền mặt" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(cbxPaymentType, gridBagConstraints);

        txtPaymentAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(txtPaymentAmount, gridBagConstraints);

        lblPaymentType.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPaymentType.setText("Hình thức thanh toán: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(lblPaymentType, gridBagConstraints);

        lblToltalTuition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToltalTuition.setText("100.000.000 VNĐ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(lblToltalTuition, gridBagConstraints);

        lblSaleOff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSaleOff.setText("50%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(lblSaleOff, gridBagConstraints);

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Huỷ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
         this.bill = new Bill(LocalDateTime.now(), Double.parseDouble(txtPaymentAmount.getText()), cbxPaymentType.getSelectedItem().toString(), registering);
         BillDAO billDAO = new BillDAO();
         if(billDAO.createBill(this.bill)){
             javax.swing.JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
             this.dispose();
             this.registerCourseFrm.dispose();
         }else{
             javax.swing.JOptionPane.showMessageDialog(this, "Thanh toán thất bại!");
         }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillFrm(null, null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cbxPaymentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlabel10;
    private javax.swing.JLabel jlabel9;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBillingDate;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnrollmentStaff;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblIDCard;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblPaymentType;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSaleOff;
    private javax.swing.JLabel lblToltalTuition;
    private javax.swing.JTable tblRegisteredClass;
    private javax.swing.JTable tblSessionList;
    private javax.swing.JTextField txtPaymentAmount;
    // End of variables declaration//GEN-END:variables
}
