/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlttnn.view;

import qlttnn.model.Registering;

/**
 *
 * @author ASUS
 */
public class BillFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillFrm.class.getName());
    private Registering registering;
    /**
     * Creates new form BillFrm
     */
    public BillFrm(Registering registering) {
        initComponents();
        this.registering = registering;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStudentInfo = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblIDCard = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        pnlRegisteredClassList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegisteredClass = new javax.swing.JTable();
        lblSale = new javax.swing.JLabel();
        lblTotalTuition = new javax.swing.JLabel();
        lblPaid = new javax.swing.JLabel();
        lblDebt = new javax.swing.JLabel();
        lblPaymentAmount = new javax.swing.JLabel();
        cbxPaymentType = new javax.swing.JComboBox<>();
        lblPaymentType = new javax.swing.JLabel();
        pnlSessionList = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSessionList = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtPaymentAmount = new javax.swing.JTextField();
        lblEnrollmentStaff = new javax.swing.JLabel();
        lblBillingDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hoá đơn");
        setBackground(new java.awt.Color(255, 255, 255));

        pnlStudentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin học viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblFullName.setBackground(new java.awt.Color(255, 255, 255));
        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblFullName.setText("Họ tên:");

        lblDateOfBirth.setBackground(new java.awt.Color(255, 255, 255));
        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDateOfBirth.setText("Ngày sinh: ");

        lblIDCard.setBackground(new java.awt.Color(255, 255, 255));
        lblIDCard.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblIDCard.setText("CCCD: ");

        lblPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPhone.setText("Số điện thoại: ");

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEmail.setText("Email: ");

        lblAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblAddress.setText("Địa chỉ: ");

        javax.swing.GroupLayout pnlStudentInfoLayout = new javax.swing.GroupLayout(pnlStudentInfo);
        pnlStudentInfo.setLayout(pnlStudentInfoLayout);
        pnlStudentInfoLayout.setHorizontalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(lblIDCard)
                    .addComponent(lblPhone)
                    .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        pnlStudentInfoLayout.setVerticalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                .addComponent(lblFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateOfBirth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIDCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress))
        );

        pnlRegisteredClassList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách lớp học đăng kí", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblRegisteredClass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblRegisteredClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Tên lớp", "Chương trình", "Mức độ", "Cơ sở", "Ngày khai giảng", "Học phí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRegisteredClass);
        if (tblRegisteredClass.getColumnModel().getColumnCount() > 0) {
            tblRegisteredClass.getColumnModel().getColumn(0).setMaxWidth(30);
            tblRegisteredClass.getColumnModel().getColumn(2).setMinWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(2).setMaxWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(4).setMaxWidth(300);
            tblRegisteredClass.getColumnModel().getColumn(5).setMinWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblRegisteredClass.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout pnlRegisteredClassListLayout = new javax.swing.GroupLayout(pnlRegisteredClassList);
        pnlRegisteredClassList.setLayout(pnlRegisteredClassListLayout);
        pnlRegisteredClassListLayout.setHorizontalGroup(
            pnlRegisteredClassListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisteredClassListLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRegisteredClassListLayout.setVerticalGroup(
            pnlRegisteredClassListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );

        lblSale.setBackground(new java.awt.Color(255, 255, 255));
        lblSale.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSale.setText("Khuyến mãi: ");

        lblTotalTuition.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalTuition.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTotalTuition.setText("Tổng tiền học phí:");

        lblPaid.setBackground(new java.awt.Color(255, 255, 255));
        lblPaid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPaid.setText("Đã thanh toán:");

        lblDebt.setBackground(new java.awt.Color(255, 255, 255));
        lblDebt.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDebt.setText("Còn nợ:");

        lblPaymentAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentAmount.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPaymentAmount.setText("Số tiền thanh toán lần này:");

        cbxPaymentType.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbxPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyển khoản", "Tiền mặt" }));
        cbxPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaymentTypeActionPerformed(evt);
            }
        });

        lblPaymentType.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentType.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPaymentType.setText("Hình thức thanh toán: ");

        pnlSessionList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách các buổi học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblSessionList.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblSessionList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Lớp học", "Ngày học", "Ca học", "Giáo viên", "Kĩ năng", "Phòng học"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSessionList);
        if (tblSessionList.getColumnModel().getColumnCount() > 0) {
            tblSessionList.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        javax.swing.GroupLayout pnlSessionListLayout = new javax.swing.GroupLayout(pnlSessionList);
        pnlSessionList.setLayout(pnlSessionListLayout);
        pnlSessionListLayout.setHorizontalGroup(
            pnlSessionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        pnlSessionListLayout.setVerticalGroup(
            pnlSessionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnCancel.setText("Huỷ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtPaymentAmount.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        lblEnrollmentStaff.setBackground(new java.awt.Color(255, 255, 255));
        lblEnrollmentStaff.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEnrollmentStaff.setText("Người tạo phiếu:");

        lblBillingDate.setBackground(new java.awt.Color(255, 255, 255));
        lblBillingDate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblBillingDate.setText("Ngày tạo phiếu: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblBillingDate)
                        .addComponent(lblEnrollmentStaff))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPaymentType)
                        .addGap(92, 92, 92)
                        .addComponent(lblDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlRegisteredClassList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalTuition)
                        .addComponent(lblSale, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnConfirm)
                                    .addComponent(cbxPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(8, 8, 8))
                        .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlSessionList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnrollmentStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBillingDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRegisteredClassList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSessionList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTotalTuition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaid)
                    .addComponent(lblDebt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentAmount)
                    .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentType)
                    .addComponent(cbxPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbxPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaymentTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillFrm(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cbxPaymentType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBillingDate;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDebt;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnrollmentStaff;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblIDCard;
    private javax.swing.JLabel lblPaid;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblPaymentType;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSale;
    private javax.swing.JLabel lblTotalTuition;
    private javax.swing.JPanel pnlRegisteredClassList;
    private javax.swing.JPanel pnlSessionList;
    private javax.swing.JPanel pnlStudentInfo;
    private javax.swing.JTable tblRegisteredClass;
    private javax.swing.JTable tblSessionList;
    private javax.swing.JTextField txtPaymentAmount;
    // End of variables declaration//GEN-END:variables
}
