/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlttnn.view;

import qlttnn.model.User;

/**
 *
 * @author ASUS
 */
public class RegisterCourseFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterCourseFrm.class.getName());
    private static User user;
    /**
     * Creates new form RegisterCourseFrm
     */
    public RegisterCourseFrm(User user) {
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCourseClassList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseClassList = new javax.swing.JTable();
        btnAddCourseClass = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        pnlStudentInfo = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblIDCard = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng kí học");
        setBackground(new java.awt.Color(255, 255, 255));

        pnlCourseClassList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách lớp đăng kí nguyện vọng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblCourseClassList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Tên lớp", "Chương trình", "Mức độ", "Cơ sở", "Ngày khai giảng", "Ngày học", "Ca học"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseClassList);
        if (tblCourseClassList.getColumnModel().getColumnCount() > 0) {
            tblCourseClassList.getColumnModel().getColumn(0).setMaxWidth(25);
            tblCourseClassList.getColumnModel().getColumn(1).setPreferredWidth(15);
            tblCourseClassList.getColumnModel().getColumn(2).setMinWidth(100);
            tblCourseClassList.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblCourseClassList.getColumnModel().getColumn(2).setMaxWidth(100);
            tblCourseClassList.getColumnModel().getColumn(3).setPreferredWidth(15);
            tblCourseClassList.getColumnModel().getColumn(4).setPreferredWidth(15);
            tblCourseClassList.getColumnModel().getColumn(5).setMinWidth(100);
            tblCourseClassList.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblCourseClassList.getColumnModel().getColumn(5).setMaxWidth(100);
            tblCourseClassList.getColumnModel().getColumn(6).setMinWidth(70);
            tblCourseClassList.getColumnModel().getColumn(6).setPreferredWidth(70);
            tblCourseClassList.getColumnModel().getColumn(6).setMaxWidth(70);
            tblCourseClassList.getColumnModel().getColumn(7).setPreferredWidth(10);
        }

        javax.swing.GroupLayout pnlCourseClassListLayout = new javax.swing.GroupLayout(pnlCourseClassList);
        pnlCourseClassList.setLayout(pnlCourseClassListLayout);
        pnlCourseClassListLayout.setHorizontalGroup(
            pnlCourseClassListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCourseClassListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCourseClassListLayout.setVerticalGroup(
            pnlCourseClassListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCourseClassListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAddCourseClass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAddCourseClass.setText("Thêm lớp học");
        btnAddCourseClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseClassActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnRegister.setText("Đăng kí");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        pnlStudentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin học viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblFullName.setBackground(new java.awt.Color(255, 255, 255));
        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblFullName.setText("Họ tên:");

        lblDateOfBirth.setBackground(new java.awt.Color(255, 255, 255));
        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDateOfBirth.setText("Ngày sinh:");

        lblPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPhone.setText("SĐT:");

        lblIDCard.setBackground(new java.awt.Color(255, 255, 255));
        lblIDCard.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblIDCard.setText("CCCD:");

        lblAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblAddress.setText("Địa chỉ:");

        javax.swing.GroupLayout pnlStudentInfoLayout = new javax.swing.GroupLayout(pnlStudentInfo);
        pnlStudentInfo.setLayout(pnlStudentInfoLayout);
        pnlStudentInfoLayout.setHorizontalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDCard, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStudentInfoLayout.setVerticalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                .addComponent(lblFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDateOfBirth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIDCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddCourseClass)
                        .addGap(26, 26, 26)
                        .addComponent(btnRegister))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlStudentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCourseClassList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCourseClassList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourseClass)
                    .addComponent(btnRegister))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCourseClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCourseClassActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterCourseFrm(user).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourseClass;
    private javax.swing.JButton btnRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblIDCard;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JPanel pnlCourseClassList;
    private javax.swing.JPanel pnlStudentInfo;
    private javax.swing.JTable tblCourseClassList;
    // End of variables declaration//GEN-END:variables
}
