/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlttnn.view;

/**
 *
 * @author ASUS
 */
public class SelectCourseClassFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectCourseClassFrm.class.getName());

    /**
     * Creates new form SearchCourseClassFrm
     */
    public SelectCourseClassFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProgramLevelInfo = new javax.swing.JPanel();
        lblProgramName = new javax.swing.JLabel();
        lblProgramDesscription = new javax.swing.JLabel();
        lblLevelName = new javax.swing.JLabel();
        lblEntryLevel = new javax.swing.JLabel();
        lblTargetLevel = new javax.swing.JLabel();
        lblTotalSession = new javax.swing.JLabel();
        lblTuition = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pnlCourseClassList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseClassList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tìm kiếm lớp học");
        setBackground(new java.awt.Color(255, 255, 255));

        pnlProgramLevelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chương trình và mức độ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblProgramName.setBackground(new java.awt.Color(255, 255, 255));
        lblProgramName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblProgramName.setText("Tên chương trình:");

        lblProgramDesscription.setBackground(new java.awt.Color(255, 255, 255));
        lblProgramDesscription.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblProgramDesscription.setText("Mô tả: ");

        lblLevelName.setBackground(new java.awt.Color(255, 255, 255));
        lblLevelName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblLevelName.setText("Tên mức độ: ");

        lblEntryLevel.setBackground(new java.awt.Color(255, 255, 255));
        lblEntryLevel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEntryLevel.setText("Đầu vào:");

        lblTargetLevel.setBackground(new java.awt.Color(255, 255, 255));
        lblTargetLevel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTargetLevel.setText("Đầu ra: ");

        lblTotalSession.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalSession.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTotalSession.setText("Thời lượng:");

        lblTuition.setBackground(new java.awt.Color(255, 255, 255));
        lblTuition.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTuition.setText("Học phí: ");

        javax.swing.GroupLayout pnlProgramLevelInfoLayout = new javax.swing.GroupLayout(pnlProgramLevelInfo);
        pnlProgramLevelInfo.setLayout(pnlProgramLevelInfoLayout);
        pnlProgramLevelInfoLayout.setHorizontalGroup(
            pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramLevelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProgramLevelInfoLayout.createSequentialGroup()
                        .addGroup(pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProgramName)
                            .addComponent(lblProgramDesscription)
                            .addComponent(lblLevelName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProgramLevelInfoLayout.createSequentialGroup()
                        .addGroup(pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTotalSession, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(lblEntryLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addGroup(pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTargetLevel)
                            .addComponent(lblTuition))
                        .addGap(96, 96, 96))))
        );
        pnlProgramLevelInfoLayout.setVerticalGroup(
            pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramLevelInfoLayout.createSequentialGroup()
                .addComponent(lblProgramName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProgramDesscription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLevelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntryLevel)
                    .addComponent(lblTargetLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProgramLevelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSession)
                    .addComponent(lblTuition))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pnlCourseClassList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách lớp học đang mở", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblCourseClassList.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblCourseClassList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Tên lớp", "Cơ sở", "Ngày khai giảng", "Ngày học", "Ca học"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseClassList);
        if (tblCourseClassList.getColumnModel().getColumnCount() > 0) {
            tblCourseClassList.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        javax.swing.GroupLayout pnlCourseClassListLayout = new javax.swing.GroupLayout(pnlCourseClassList);
        pnlCourseClassList.setLayout(pnlCourseClassListLayout);
        pnlCourseClassListLayout.setHorizontalGroup(
            pnlCourseClassListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseClassListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCourseClassListLayout.setVerticalGroup(
            pnlCourseClassListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseClassListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlCourseClassList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlProgramLevelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProgramLevelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCourseClassList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SelectCourseClassFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntryLevel;
    private javax.swing.JLabel lblLevelName;
    private javax.swing.JLabel lblProgramDesscription;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblTargetLevel;
    private javax.swing.JLabel lblTotalSession;
    private javax.swing.JLabel lblTuition;
    private javax.swing.JPanel pnlCourseClassList;
    private javax.swing.JPanel pnlProgramLevelInfo;
    private javax.swing.JTable tblCourseClassList;
    // End of variables declaration//GEN-END:variables
}
