/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlttnn.view;

import qlttnn.dao.LevelDAO;
import qlttnn.dao.ProgramDAO;
import qlttnn.model.Level;
import qlttnn.model.Program;
import qlttnn.model.Registering;
import qlttnn.model.Student;


import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

import static javax.swing.SwingUtilities.isLeftMouseButton;

/**
 *
 * @author ASUS
 */
public class SelectProgramLevelFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectProgramLevelFrm.class.getName());
    private Registering registering;
    private ArrayList<Program> programs = new ArrayList<>();
    private ArrayList<Level> levels = new ArrayList<>();
    private RegisterCourseFrm registerCourseFrm;
    /**
     * Creates new form SelectProgramLevelFrm
     */
    public SelectProgramLevelFrm(Registering registering, RegisterCourseFrm registerCourseFrm) {
        initComponents();
        this.registering = registering;
        this.registerCourseFrm = registerCourseFrm;
        loadProgramData();

    }
    public SelectProgramLevelFrm(){

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSelectProgram = new javax.swing.JPanel();
        cbxProgram = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLevelList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chọn chương trình và mức độ");
        setBackground(new java.awt.Color(255, 255, 255));

        pnlSelectProgram.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn chương trình", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        cbxProgram.setEditable(true);
        cbxProgram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        //cbxProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IELTS", "TOEIC LR", "TOEIC RW", "TOEFL" }));
        cbxProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSelectProgramLayout = new javax.swing.GroupLayout(pnlSelectProgram);
        pnlSelectProgram.setLayout(pnlSelectProgramLayout);
        pnlSelectProgramLayout.setHorizontalGroup(
            pnlSelectProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxProgram, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSelectProgramLayout.setVerticalGroup(
            pnlSelectProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectProgramLayout.createSequentialGroup()
                .addComponent(cbxProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách mức độ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblLevelList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TT", "Tên mức độ", "Đầu vào", "Đầu ra", "Thời lượng", "Học phí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLevelList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLevelListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLevelList);
        if (tblLevelList.getColumnModel().getColumnCount() > 0) {
            tblLevelList.getColumnModel().getColumn(0).setMinWidth(50);
            tblLevelList.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblLevelList.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSelectProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSelectProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadProgramData(){
        ProgramDAO programDAO = new ProgramDAO();
        programs = programDAO.getProgramList();
        cbxProgram.removeAllItems();
        for(Program program: programs){
            cbxProgram.addItem(program);
        }
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void cbxProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProgramActionPerformed
        // TODO add your handling code here:
        if (cbxProgram.getItemCount() > 0 && cbxProgram.getSelectedIndex() != -1) {
            Program selectedProgram = (Program) cbxProgram.getSelectedItem();
            if (selectedProgram != null) {
                LevelDAO levelDAO = new LevelDAO();
                levels = levelDAO.getLevelList(selectedProgram);

                DefaultTableModel defaultTableModel = (DefaultTableModel) tblLevelList.getModel();
                defaultTableModel.setRowCount(0);
                int stt = 0;
                for (Level level : levels) {
                    defaultTableModel.addRow(new Object[]{
                            ++stt,
                            level.getLevelName(),
                            level.getEntryLevel(),
                            level.getTargetLevel(),
                            level.getTotalSessions(),
                            level.getTuition()
                    });
                }

            }
        }

    }//GEN-LAST:event_cbxProgramActionPerformed

    private void tblLevelListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLevelListMouseClicked
        // TODO add your handling code here:
        int row = tblLevelList.rowAtPoint(evt.getPoint());
        if(row == -1)
            return;
        if(isLeftMouseButton(evt) && evt.getClickCount() == 2){
            Level level = this.levels.get (row);
            SelectCourseClassFrm selectCourseClassFrm = new SelectCourseClassFrm(this.registering, level, this.registerCourseFrm, this);
            selectCourseClassFrm.setVisible(true);
        }
    }//GEN-LAST:event_tblLevelListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SelectProgramLevelFrm(new Registering(), new RegisterCourseFrm()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<Program> cbxProgram;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlSelectProgram;
    private javax.swing.JTable tblLevelList;
    // End of variables declaration//GEN-END:variables
}
