/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlttnn.view;

import qlttnn.dao.CourseClassDAO;
import qlttnn.model.*;


import javax.swing.table.DefaultTableModel;
import java.time.DayOfWeek;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;

import static javax.swing.SwingUtilities.computeUnion;
import static javax.swing.SwingUtilities.isLeftMouseButton;

/**
 *
 * @author ASUS
 */
public class SelectCourseClassFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectCourseClassFrm.class.getName());
    private Registering registering;
    private Level level;
    private ArrayList<CourseClass> courseClasses = new ArrayList<>();
    private CourseClassDAO courseClassDAO = new CourseClassDAO();
    private RegisterCourseFrm registerCourseFrm;
    private SelectProgramLevelFrm selectProgramLevelFrm;
    /**
     * Creates new form SearchCourseClassFrm
     */
    public SelectCourseClassFrm(Registering registering,  Level level, RegisterCourseFrm registerCourseFrm, SelectProgramLevelFrm selectProgramLevelFrm) {
        initComponents();
        setLocationRelativeTo(null);
        this.registering = registering;
        this.level = level;
        this.registerCourseFrm = registerCourseFrm;
        this.selectProgramLevelFrm = selectProgramLevelFrm;
        this.lblProgramName.setText(this.level.getProgram().getProgramName());
        this.lblLevelName.setText(this.level.getLevelName());
        this.lblEntryLevel.setText(String.valueOf(this.level.getEntryLevel()));
        this.lblTargetLevel.setText(String.valueOf(this.level.getTargetLevel()));
        this.lblTotalSession.setText(String.format("%d buổi",this.level.getTotalSessions()));
        this.lblTuition.setText(String.format("%,.0f VNĐ",this.level.getTuition()));

        loadCourseClassData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblProgramName = new javax.swing.JLabel();
        lblLevelName = new javax.swing.JLabel();
        lblEntryLevel = new javax.swing.JLabel();
        lblTargetLevel = new javax.swing.JLabel();
        lblTotalSession = new javax.swing.JLabel();
        lblTuition = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseClassList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tìm kiếm lớp học");
        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chương trình"));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Tên chương trình:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel3.setText("Mức độ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Đầu vào:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Đầu ra:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Thời lượng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Học phí:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel7, gridBagConstraints);

        lblProgramName.setText("IELTS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblProgramName, gridBagConstraints);

        lblLevelName.setText("IELTS 4.5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblLevelName, gridBagConstraints);

        lblEntryLevel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblEntryLevel, gridBagConstraints);

        lblTargetLevel.setText("4.5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblTargetLevel, gridBagConstraints);

        lblTotalSession.setText(" 30 buổi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblTotalSession, gridBagConstraints);

        lblTuition.setText("10.000.000 VNĐ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblTuition, gridBagConstraints);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách lớp học đang mở"));

        tblCourseClassList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Tên lớp", "Cơ sở", "Ngày khai giảng", "Ngày học", "Ca học"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourseClassList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseClassListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourseClassList);
        if (tblCourseClassList.getColumnModel().getColumnCount() > 0) {
            tblCourseClassList.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadCourseClassData(){
        courseClasses = courseClassDAO.getCourseClassList(level);
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblCourseClassList.getModel();
        defaultTableModel.setRowCount(0);
        int stt = 0;
        for (CourseClass cc : courseClasses) {
            defaultTableModel.addRow(new Object[]{
                    ++stt,
                    cc.getClassName(),
                    cc.getBranch().getBranchName(),
                    cc.getStartDate(),
                    cc.getDay(),
                    cc.getShiftDay()
            });
        }
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void tblCourseClassListMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblCourseClassList.rowAtPoint(evt.getPoint());
        if(row == -1)
            return;
        if(isLeftMouseButton(evt) && evt.getClickCount() == 2){
            CourseClass courseClass = courseClasses.get(row);

            // Kiểm tra trùng với lớp ĐANG HỌC
            String conflictClassName = courseClassDAO.findConflictClass(courseClass, registering.getStudent());
            if(conflictClassName != null){
                javax.swing.JOptionPane.showMessageDialog(this, "Lớp bạn đang chọn đã bị trùng lịch học với lớp " + conflictClassName+ " bạn đang học tại trung tâm\nVui lòng chọn lớp khác!");
                return;
            }
            // Kiem tra trung lich lop da chọn
            for(Session session: courseClass.getSessions()) {
                System.out.println(session);
                for(RegisteredClass registeredClass: registering.getRegisteredClasses()) {
                    if(registeredClass.getCourseClass().getSessions().contains(session)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Lớp bạn đang chọn đã bị trùng lịch học với lớp " + registeredClass.getCourseClass().getClassName() +" đã chọn\nVui lòng chọn lớp khác!");
                        return;
                    }
                }
            }

            // Không trùng với cả lớp đang học VÀ lớp đã chọn

            RegisteredClass registeredClass = new RegisteredClass(courseClass, level.getTuition());
            registering.setRegisteredClasses(registeredClass);
            this.dispose();
            this.selectProgramLevelFrm.dispose();
            registerCourseFrm.reloadRegisterTbl();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SelectCourseClassFrm(new Registering(), new Level(), new RegisterCourseFrm(), new SelectProgramLevelFrm()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntryLevel;
    private javax.swing.JLabel lblLevelName;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblTargetLevel;
    private javax.swing.JLabel lblTotalSession;
    private javax.swing.JLabel lblTuition;
    private javax.swing.JTable tblCourseClassList;
    // End of variables declaration//GEN-END:variables
}
